#!/usr/bin/env bash
# Configures /etc/hosts so that:
#   localhost resolves to 127.0.0.2
#   facebook.com resolves to 8.8.8.8

cp /etc/hosts /tmp/hosts_modified

sed -i 's/127\.0\.0\.1\(\s\+\)localhost/127.0.0.2\1localhost/' /tmp/hosts_modified

if grep -q 'facebook\.com' /tmp/hosts_modified; then
    sed -i 's/.*facebook\.com.*/8.8.8.8\tfacebook.com/' /tmp/hosts_modified
else
    echo '8.8.8.8	facebook.com' >> /tmp/hosts_modified
fi

cp /tmp/hosts_modified /etc/hosts
